In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
from matplotlib import pyplot
import PIL



In [ ]:
print(tf.__version__)

In [3]:
# loading data fashion_mnist
fashion_minist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_minist.load_data()
 

In [4]:
# what does these values look like?
import numpy as np
np.set_printoptions(linewidth=200)
import matplotlib.pyplot as plt
plt.imshow(train_images[0], cmap='gray')
#print(train_labels[0])
print(train_images[0])
print(train_images[0].shape)


[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0   0  13  73   0   0   1   4   0   0   0   0   1   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3   0  36 136 127  62  54   0   0   0   1   3   4   0   0   3]
 [  0   0   0   0   0   0   0   0   0   0   0   0   6   0 102 204 176 134 144 123  23   0   0   0   0  12  10   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0 155 236 207 178 107 156 161 109  64  23  77 130  72  15]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0  69 207 223 218 216 216 163 127 121 122 146 141  88 172  66]
 [  0   0   0   0   0   0   0   0   0   1   1   1   0 200 232 232 233 229 223 22

In [5]:
# you'll notice that all of the values in the number are between 0 and 255.
# if we are training a neural network, for various reasons it's easier if we treat all values as between 0 and 1,
# a process normalizing and fortunately in python it's easy to normalize a list like 
# this without looping 
train_images = train_images / 255.0
test_images = test_images / 255.0

In [7]:
# Let's now design the model
model = keras.Sequential([
    # input layer images 28X 28
    keras.layers.Flatten(input_shape=(28,28)),
    # hidden layer - 128 neurons
    keras.layers.Dense(128, activation=tf.nn.relu),
    # output layers because we have ten classes of clothing in the dataset.
    keras.layers.Dense(10, activation=tf.nn.softmax)
])



**Sequential** : the defines a SEQUENCE of layers in the neural network

**Flatten** : remember earlier where our images were a square, when you printed them out? Flatten just takes that square and turns it into a 1 dimensonal set

**Dense** : adds a layers of neurons

each layers fo neurons need an **activation function** to tell them what to do.

**Rule** : effectively means if X>0 return X, else return 0

**Softmax** : takes a set of values, and effectively picks the bigges one. ex) [0.1, 0.2, 9.5] -> [0,0,1]. The goal is to save a lot of coding!

The next thing to do, now model is defined, is to actually build it. You do this by compling it with an optimizer and loss function as befroe. and then you train it by calling **model.fit** asking it to fit your trainig data to your training labels


In [9]:
model.compile(optimizer=keras.optimizers.Adam(),loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(train_images,train_labels,epochs=5)


Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.6282 - accuracy: 0.7838
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3854 - accuracy: 0.8616
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3397 - accuracy: 0.8751
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3125 - accuracy: 0.8860
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2917 - accuracy: 0.8917


once it's done training -- you show see an accuray value at the end of the final epoch. it might look like something like 0.9098. This tells you that your neural network is about 91% accurate in classifying the training data. IE,. it figured out a pattern match between the image and the labels that worked 91% of the time. Not great, but not bad considering it was only trained for 5 epochs and done quite quickly

But how would it work with unseen data? That's why we have the test images. We call model.evalute, and pass in the two sets, and it will report back the loss for each. Let's give it a try

In [14]:
model.evaluate(test_images,test_labels)


313/313 [==============================] - 0s 958us/step - loss: 0.3425 - accuracy: 0.8736


[0.3424607813358307, 0.8736000061035156]

## Excersie 1:
below code prints the first entry in the classifications. The output, after you run it is a list of numbers. Why do you think is, and what do those numbers present?

In [25]:
classifications = model.predict(test_images)
print(classifications.shape)
print(classifications[0])


(10000, 10)
[2.8781426e-06 6.3117223e-09 2.2734035e-07 9.3454176e-08 1.2203843e-07 1.7341126e-02 9.5476287e-07 1.1918182e-01 1.8200928e-06 8.6347091e-01]


In [16]:
print(test_labels[0])

9


## Question1 : What does this list present?
it's the probability that this item is each of the 10 classes
ans)
The output of the modle is a list of 10 numbers. These numbers are a probability that the value being classified is the corresponding value, i.e, the first value in the list is the probability that the image is of a '0' the next is a '1' etc
For index 9(Ankle boot) the probability was in the 90% i.e. the neural network is telling us that the image is most likely an ankle boot

## Question 2 : How do you know that this list tells you that the item is an ankle boot?

The 10th element on the list is the biggest, and the ankle boot is labelled 9
## Answer
Both the list and labels are 0 based, so the ankle boot having label 9 means that it is the 10th of th 10 classes. The list having the 10th element being values means that the Neural Network has predicted that the item it is classifying is most likely an ankle boot

## Exercise 2 
experiment with different values for the dense layer with 512 neurons. What different results do you get for loss, training time etc? Why do you think that's the case?

In [27]:
mnst = tf.keras.datasets.mnist

# load data and normalizing 
(train_images, train_labels),(test_images,test_labels) = mnst.load_data()
train_images = train_images / 255.0
test_images = test_images / 255.0
