In [10]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt



In [ ]:
print(tf.__version__)

In [3]:
# loading data fashion_mnist
fashion_minist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_minist.load_data()
 

In [4]:
# what does these values look like?
import numpy as np
np.set_printoptions(linewidth=200)
import matplotlib.pyplot as plt
plt.imshow(train_images[0], cmap='gray')
#print(train_labels[0])
print(train_images[0])
print(train_images[0].shape)


[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0   0  13  73   0   0   1   4   0   0   0   0   1   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3   0  36 136 127  62  54   0   0   0   1   3   4   0   0   3]
 [  0   0   0   0   0   0   0   0   0   0   0   0   6   0 102 204 176 134 144 123  23   0   0   0   0  12  10   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0 155 236 207 178 107 156 161 109  64  23  77 130  72  15]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0  69 207 223 218 216 216 163 127 121 122 146 141  88 172  66]
 [  0   0   0   0   0   0   0   0   0   1   1   1   0 200 232 232 233 229 223 22

In [5]:
# you'll notice that all of the values in the number are between 0 and 255.
# if we are training a neural network, for various reasons it's easier if we treat all values as between 0 and 1,
# a process normalizing and fortunately in python it's easy to normalize a list like 
# this without looping 
train_images = train_images / 255.0
test_images = test_images / 255.0

In [7]:
# Let's now design the model
model = keras.Sequential([
    # input layer images 28X 28
    keras.layers.Flatten(input_shape=(28,28)),
    # hidden layer - 128 neurons
    keras.layers.Dense(128, activation=tf.nn.relu),
    # output layers because we have ten classes of clothing in the dataset.
    keras.layers.Dense(10, activation=tf.nn.softmax)
])



**Sequential** : the defines a SEQUENCE of layers in the neural network

**Flatten** : remember earlier where our images were a square, when you printed them out? Flatten just takes that square and turns it into a 1 dimensonal set

**Dense** : adds a layers of neurons

each layers fo neurons need an **activation function** to tell them what to do.

**Rulu** effectively means if X>0 return X, else return 0

**Softmax** : takes a set of values, and effectively picks the bigges one. ex) [0.1, 0.2, 9.5] -> [0,0,1]. The goal is to save a lot of coding!

The next thing to do, now model is defined, is to actually build it. You do this by compling it with an optimizer and loss function as befroe. and then you train it by calling **model.fit** asking it to fit your trainig data to your training labels


In [9]:
model.compile(optimizer=keras.optimizers.Adam(),loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(train_images,train_labels,epochs=5)


Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.6282 - accuracy: 0.7838
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3854 - accuracy: 0.8616
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3397 - accuracy: 0.8751
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3125 - accuracy: 0.8860
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2917 - accuracy: 0.8917


once it's done training -- you show see an accuray value at the end of the final epoch. it might look like something like 0.9098. This tells you that your neural network is about 91% accurate in classifying the training data. IE,. it figured out a pattern match between the image and the labels that worked 91% of the time. Not great, but not bad considering it was only trained for 5 epochs and done quite quickly

But how would it work with unseen data? That's why we have the test images. We call model.evalute, and pass in the two sets, and it will report back the loss for each. Let's give it a try

In [14]:
model.evaluate(test_images,test_labels)


313/313 [==============================] - 0s 958us/step - loss: 0.3425 - accuracy: 0.8736


[0.3424607813358307, 0.8736000061035156]

## Excersie 1:
below code prints the first entry in the classifications. The output, after you run it is a list of numbers. Why do you think is, and what do those numbers present?

In [25]:
classifications = model.predict(test_images)
print(classifications.shape)
print(classifications[0])


(10000, 10)
[2.8781426e-06 6.3117223e-09 2.2734035e-07 9.3454176e-08 1.2203843e-07 1.7341126e-02 9.5476287e-07 1.1918182e-01 1.8200928e-06 8.6347091e-01]


In [16]:
print(test_labels[0])

9


### Question1 : What does this list present?
it's the probability that this item is each of the 10 classes
ans)
The output of the modle is a list of 10 numbers. These numbers are a probability that the value being classified is the corresponding value, i.e, the first value in the list is the probability that the image is of a '0' the next is a '1' etc
For index 9(Ankle boot) the probability was in the 90% i.e. the neural network is telling us that the image is most likely an ankle boot

### Question 2 : How do you know that this list tells you that the item is an ankle boot?

### Answer
The 10th element on the list is the biggest, and the ankle boot is labelled 9

Both the list and labels are 0 based, so the ankle boot having label 9 means that it is the 10th of th 10 classes. The list having the 10th element being values means that the Neural Network has predicted that the item it is classifying is most likely an ankle boot

## Exercise 2 
experiment with different values for the dense layer with 512 neurons. What different results do you get for loss, training time etc? Why do you think that's the case?

In [44]:
tf.keras.backend.clear_session()
mnst = tf.keras.datasets.mnist

# load data and normalizing 
(train_images, train_labels),(test_images,test_labels) = mnst.load_data()
train_images = train_images / 255.0
test_images = test_images / 255.0

print(f'train images shape :{train_images.shape}')
print(f'test images shape :{test_images.shape}')

# design model
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    # 128 : 0.9763
    # 512 : 0.9810 
    # 1024 : 
    tf.keras.layers.Dense(1024, activation=tf.nn.relu),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

# compile model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy']
             )
# training model
model.fit(train_images,train_labels, epochs=5)

# evaluate model
model.evaluate(test_images,test_labels)

clssification = model.predict(test_images)
print(classifications[0])
print(test_labels[0])


train images shape :(60000, 28, 28)
test images shape :(10000, 28, 28)
Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3160 - accuracy: 0.9040
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0747 - accuracy: 0.9770
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0454 - accuracy: 0.9847
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0307 - accuracy: 0.9905
Epoch 5/5
313/313 [==============================] - 1s 1ms/step - loss: 0.0773 - accuracy: 0.9794
[2.8781426e-06 6.3117223e-09 2.2734035e-07 9.3454176e-08 1.2203843e-07 1.7341126e-02 9.5476287e-07 1.1918182e-01 1.8200928e-06 8.6347091e-01]
7


### Question1 : Increase to 1024 neurons -- What's the impact?
### Answer
Training takes longer, but is more accurate
adding more Neurons we have to do more caculations, slowing down the process, but in this case they have a good impact -- we do get more accurate. That doesn't mean it's always a case of 'more is better', you can hit the law of diminishing returns very quickly!

## Excersie3 
### Question1 : What would happen if you remove the Flatten()layer. Why do the think that's the case?
### Answer 
you get an error about **the shape of the data**. it may seem vague right now, but it reinforces the rule of thumb that the first layers in you network should be the same shape as your data. Right now our data is 28X28 images, and 28 layers of 28 neurons would be infeasilbe, so it makes more sense to **flatten** 28,28 into to 784X1. we add the Flatten() layer at the begining, and when the arrays are loaded into the model layres, they'll automatically be flattened for us

In [50]:
mnist = tf.keras.datasets.mnist

(training_images, training_labels) ,  (test_images, test_labels) = mnist.load_data()

training_images = training_images/255.0
test_images = test_images/255.0

model = tf.keras.models.Sequential([tf.keras.layers.Flatten(), #Try removing this layer
                                    tf.keras.layers.Dense(64, activation=tf.nn.relu),
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)])

model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy')

model.fit(training_images, training_labels, epochs=5)

model.evaluate(test_images, test_labels)

classifications = model.predict(test_images)



Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.5011
Epoch 2/5
1875/1875 [==============================] - 2s 940us/step - loss: 0.1581
Epoch 3/5
1875/1875 [==============================] - 2s 978us/step - loss: 0.1082
Epoch 4/5
1875/1875 [==============================] - 2s 928us/step - loss: 0.0832
Epoch 5/5
313/313 [==============================] - 0s 724us/step - loss: 0.0919
[6.4534324e-06 1.8369107e-08 5.9857244e-05 1.2589046e-03 4.8710529e-09 6.6407875e-07 1.7532837e-12 9.9857605e-01 6.5446902e-06 9.1570699e-05]
7
7


In [54]:
print(classifications[0])
print(type(classifications))
print(np.argmax(classifications[0],axis=0))
print(test_labels[0])

[6.4534324e-06 1.8369107e-08 5.9857244e-05 1.2589046e-03 4.8710529e-09 6.6407875e-07 1.7532837e-12 9.9857605e-01 6.5446902e-06 9.1570699e-05]
<class 'numpy.ndarray'>
7
7


## Excersie4
Consider the final (output) layers. Why are there 10 of them? What would happen if you had a different amount than 10? For example, try training the network with 5.

### Answer 
You get an error as soon as it finds an unexpected value. Another rule of thumb -- the number of neurons in the last layer should match the number of classes you are classifying for. In this case it's the digits 0-9, so there are 10 of them, hence you should have 10 neurons in your final layer.

In [ ]:
mnist = tf.keras.datasets.mnist

(training_images, training_labels) ,  (test_images, test_labels) = mnist.load_data()

training_images = training_images/255.0
test_images = test_images/255.0

model = tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                    tf.keras.layers.Dense(64, activation=tf.nn.relu),
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax) # Try experimenting with this layer
                                  ])

model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy')

model.fit(training_images, training_labels, epochs=5)

model.evaluate(test_images, test_labels)

classifications = model.predict(test_images)

print(classifications[0])
print(test_labels[0])

## Exercise 5:
Consider the effects of additional layers in the network. What will happen if you add another layer between the one with 512 and the final layer with 10.

## Answer
There isn't a significant impact -- because this is relatively simple data. For far more complex data (including color images to be classified as flowers that you'll see in the next lesson), extra layers are often necessary.

In [63]:
tf.keras.backend.clear_session()
mnist = tf.keras.datasets.mnist

(training_images, training_labels) ,  (test_images, test_labels) = mnist.load_data()

training_images = training_images/255.0
test_images = test_images/255.0

model = tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                    tf.keras.layers.Dense(512, activation=tf.nn.relu),
                                    # Add a layer here,
                                    tf.keras.layers.Dense(256, activation=tf.nn.relu),
                                    # Add a layer here
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
                                  ])

model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy')

model.fit(training_images, training_labels, epochs=5)

model.evaluate(test_images, test_labels)

classifications = model.predict(test_images)

print(classifications[0])
print(test_labels[0])
# 256 - 0.0708
# 512 added layer - 0.0796

Epoch 1/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3186
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0823
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0529
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0421
Epoch 5/5
313/313 [==============================] - 0s 1ms/step - loss: 0.0796
[1.2698566e-13 2.7966878e-09 1.8509303e-11 6.6183361e-09 2.4037521e-12 1.2914541e-13 1.0179236e-15 9.9999988e-01 4.6263856e-12 6.5267649e-08]
7


## Exercise 6
### E6Q1: Consider the impact of training for more or less epochs. Why do you think that would be the case?
Try 15 epochs -- you'll probably get a model with a much better loss than the one with 5
Try 30 epochs -- you might see the loss value stops decreasing, and sometimes increases.
This is a side effect of something called **'overfitting'** which you can learn about later and it's something you need to keep an eye out for when training neural networks. There's no point in wasting your time training if you aren't improving your loss, right! :)

In [5]:
tf.keras.backend.clear_session()

mnist = tf.keras.datasets.mnist

(training_images, training_labels) ,  (test_images, test_labels) = mnist.load_data()

training_images = training_images/255.0
test_images = test_images/255.0

model = tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                    tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)])

model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy')
# 5 - 0.0806 loss
# 15 - 0.0928
# 30 - 0.1143
model.fit(training_images, training_labels, epochs=30) # Experiment with the number of epochs

model.evaluate(test_images, test_labels)

classifications = model.predict(test_images)

print(classifications[34])

Epoch 1/30
1875/1875 [==============================] - 2s 825us/step - loss: 0.4204
Epoch 2/30
1875/1875 [==============================] - 1s 789us/step - loss: 0.1236
Epoch 3/30
1875/1875 [==============================] - 2s 849us/step - loss: 0.0809
Epoch 4/30
1875/1875 [==============================] - 2s 821us/step - loss: 0.0550
Epoch 5/30
1875/1875 [==============================] - 2s 849us/step - loss: 0.0422
Epoch 6/30
1875/1875 [==============================] - 2s 887us/step - loss: 0.0316
Epoch 7/30
1875/1875 [==============================] - 2s 957us/step - loss: 0.0242
Epoch 8/30
1875/1875 [==============================] - 2s 949us/step - loss: 0.0212
Epoch 9/30
1875/1875 [==============================] - 2s 956us/step - loss: 0.0161
Epoch 10/30
1875/1875 [==============================] - 2s 937us/step - loss: 0.0124
Epoch 11/30
1875/1875 [==============================] - 2s 946us/step - loss: 0.0109
Epoch 12/30
1875/1875 [==============================] - 2s 1ms

## Exercise 7:
Before you trained, you normalized the data, going from values that were 0-255 to values that were 0-1. What would be the impact of removing that? Here's the complete code to give it a try. Why do you think you get different results?

In [13]:
tf.keras.backend.clear_session()
mnist = tf.keras.datasets.mnist
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()
#training_images=training_images/255.0 # Experiment with removing this line
#test_images=test_images/255.0 # Experiment with removing this line
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')
model.fit(training_images, training_labels, epochs=5)
model.evaluate(test_images, test_labels)
classifications = model.predict(test_images)
print(classifications[0])
print(test_labels[0])

# 0.0908


Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 7.3154
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3090
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2692
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2584
Epoch 5/5
313/313 [==============================] - 0s 907us/step - loss: 0.4082
[2.5989753e-28 6.2591915e-34 4.5202972e-18 6.6686331e-23 1.2824032e-33
 0.0000000e+00 0.0000000e+00 1.0000000e+00 8.7729921e-35 3.0726676e-17]
7


## Exercise 8:
Earlier when you trained for extra epochs you had an issue where your loss might change. It might have taken a bit of time for you to wait for the training to do that, and you might have thought 'wouldn't it be nice if I could stop the training when I reach a desired value?' -- i.e. 95% accuracy might be enough for you, and if you reach that after 3 epochs, why sit around waiting for it to finish a lot more epochs....So how would you fix that? Like any other program...you have callbacks! Let's see them in action...

In [18]:
class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self,epoch, logs={}):
        if logs.get('accuracy') >=0.9:
            print("\n Reached 60% accuaracy so cacelling training!!")
            self.model.stop_training=True

callbacks = myCallback()
mnist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
train_images = train_images /255.0
test_images = test_images /255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation=tf.nn.relu),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy', 
              metrics =['accuracy'])

model.fit(train_images,train_labels, epochs=10, callbacks=[callbacks])

Epoch 1/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.5898 - accuracy: 0.7905
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3640 - accuracy: 0.8667
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3266 - accuracy: 0.8798
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2995 - accuracy: 0.8895
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2798 - accuracy: 0.8944
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2657 - accuracy: 0.9000

 Reached 60% accuaracy so cacelling training!!
